FROM php:8.2-fpm

# Install dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-install zip pdo pdo_mysql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory
WORKDIR /var/www
ENV COMPOSER_ALLOW_SUPERUSER=1

# Copy the rest of the project files
COPY . .
# Copy composer files and install dependencies=
RUN composer install
# Expose port
EXPOSE 9000

# Start PHP-FPM
CMD ["php-fpm"]
